<a href="https://colab.research.google.com/github/denizgurzihin/DecisionTree-NaiveBayes-SVM-ANN/blob/main/DecisionTree%2C%20NaiveBayes%2C%20SVM%2C%20ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Decision Tree Using Gain Ratio***

***1) With Holdout Method***

In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn.metrics import *
from time import time

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

#DATA.info()
feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']

X = DATA[feature_cols] # Features
y = DATA.label # Target variable

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0
timee = 0

for x in range(10):
  test_start = time()
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=x) # 80% training and 20% test

  # Create Decision Tree classifer object
  clf = DecisionTreeClassifier(criterion="entropy")

  # Train Decision Tree Classifer
  clf = clf.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = clf.predict(X_test)
  
  accuracy = accuracy + accuracy_score(y_test, y_pred)
  f1 = f1 + f1_score(y_test, y_pred, average='weighted')
  precision = precision + precision_score(y_test, y_pred, average='weighted')
  recall = recall + recall_score(y_test, y_pred, average='weighted')
  Confusion_Matrix = Confusion_Matrix + confusion_matrix(y_test, y_pred)
  test_finish = time()
  timee = timee + test_finish-test_start

print("Overall accuracy for decision tree with gain ratio and hold out method(10 times) :", accuracy/10)
print("Overall f1_score for decision tree with gain ratio and hold out method(10 times) :", f1/10)
print("Overall precision_score for decision tree with gain ratio and hold out method(10 times) :", precision/10)
print("Overall recall_score for decision tree with gain ratio and hold out method(10 times) :", recall/10)

print("       Confusion Matrix : ")
print(Confusion_Matrix/10)

print("Overall time needed for decision tree with gain ratio and hold out method(10 times) :", ((timee/10)*10*10*10), " miliseconds")


Overall accuracy for decision tree with gain ratio and hold out method(10 times) : 0.7381018518518518
Overall f1_score for decision tree with gain ratio and hold out method(10 times) : 0.7432142648062039
Overall precision_score for decision tree with gain ratio and hold out method(10 times) : 0.7494627752881005
Overall recall_score for decision tree with gain ratio and hold out method(10 times) : 0.7381018518518518
       Confusion Matrix : 
[[172.   78.   84.8  15.1]
 [ 99.4 704.2  36.9  28.3]
 [103.5  34.7 691.5  28.9]
 [ 13.1  21.1  21.9  26.6]]
Overall time needed for decision tree with gain ratio and hold out method(10 times) : 34.22291278839111  miliseconds


***2) With K Fold Cross-validation Method***

In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn import model_selection
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import *

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']

X = DATA[feature_cols] # Features
y = DATA.label # Target variable

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0
timee = 0

scoring = ['accuracy', 'f1_weighted', 'precision_weighted', 'recall_weighted']

for i in range(10):
  test_start = time()
  kfold = model_selection.KFold(n_splits=5, shuffle=True, random_state = i )
  model = DecisionTreeClassifier(criterion="entropy")

  results = model_selection.cross_validate(model, X, y, cv=kfold, scoring=scoring)
  accuracy = accuracy + results['test_accuracy'].mean()
  f1 = f1 + results['test_f1_weighted'].mean()
  precision = precision + results['test_precision_weighted'].mean()
  recall = recall + results['test_recall_weighted'].mean()
  test_finish = time()
  timee = timee + test_finish-test_start

  y_pred = cross_val_predict(model, X, y, cv=kfold)
  Confusion_Matrix = Confusion_Matrix + confusion_matrix(y, y_pred)

print("Overall accuracy for decision tree with gain ratio and K Fold cross valdiation(10 times) :", accuracy/10)
print("Overall f1_score for decision tree with gain ratio and K Fold cross valdiation(10 times) :", f1/10)
print("Overall precision_score for decision tree with gain ratio and K Fold cross valdiation(10 times) :", precision/10)
print("Overall recall_score for decision tree with gain ratio and K Fold cross valdiation(10 times) :", recall/10)

print("       Confusion Matrix : ")
print(Confusion_Matrix/10)

print("Overall time needed for decision tree with gain ratio and K Fold cross valdiation(10 times) :", ((timee/10)*10*10*10), " miliseconds")

Overall accuracy for decision tree with gain ratio and K Fold cross valdiation(10 times) : 0.7397314814814815
Overall f1_score for decision tree with gain ratio and K Fold cross valdiation(10 times) : 0.7439006327894975
Overall precision_score for decision tree with gain ratio and K Fold cross valdiation(10 times) : 0.7489958833974054
Overall recall_score for decision tree with gain ratio and K Fold cross valdiation(10 times) : 0.7397314814814815
       Confusion Matrix : 
[[ 868.6  408.   433.3   76.1]
 [ 464.8 3509.4  185.4  146.4]
 [ 508.7  174.4 3469.4  147.5]
 [  70.    98.8  104.8  134.4]]
Overall time needed for decision tree with gain ratio and K Fold cross valdiation(10 times) : 154.81994152069092  miliseconds


 ***3) Bagging with cross validation***

In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.ensemble import BaggingClassifier
from sklearn import model_selection
from sklearn.model_selection import KFold


col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']

x = DATA[feature_cols] # Features
y = DATA.label # Target variable

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0
timee = 0

scoring = ['accuracy', 'f1_weighted', 'precision_weighted', 'recall_weighted']

for i in range(10):
  test_start = time()
  kfold = model_selection.KFold(n_splits=10, shuffle=True, random_state=i)
  dt = DecisionTreeClassifier(criterion="entropy")
  model = BaggingClassifier(base_estimator=dt, random_state=i)

  results = model_selection.cross_validate(model, X, y, cv=kfold, scoring=scoring)

  accuracy = accuracy + results['test_accuracy'].mean()
  f1 = f1 + results['test_f1_weighted'].mean()
  precision = precision + results['test_precision_weighted'].mean()
  recall = recall + results['test_recall_weighted'].mean()
  test_finish = time()
  timee = timee + test_finish-test_start

  y_pred = cross_val_predict(model, X, y, cv=kfold)
  Confusion_Matrix = Confusion_Matrix + confusion_matrix(y, y_pred)


print("Overall accuracy for decision tree with gain ratio and Bagging with K-Fold Cross Validation :", accuracy/10)
print("Overall f1_score for decision tree with gain ratio and Bagging with K-Fold Cross Validation :", f1/10)
print("Overall precision_score for decision tree with gain ratio and Bagging with K-Fold Cross Validation :", precision/10)
print("Overall recall_score for decision tree with gain ratio and Bagging with K-Fold Cross Validation :", recall/10)

print("       Confusion Matrix : ")
print(Confusion_Matrix/10)

print("Overall time needed for decision tree with gain ratio and Bagging with K-Fold Cross Validation :", ((timee/10)*10*10*10), " miliseconds")

Overall accuracy for decision tree with gain ratio and Bagging with K-Fold Cross Validation : 0.7904722222222222
Overall f1_score for decision tree with gain ratio and Bagging with K-Fold Cross Validation : 0.7885554846696445
Overall precision_score for decision tree with gain ratio and Bagging with K-Fold Cross Validation : 0.7880436538169946
Overall recall_score for decision tree with gain ratio and Bagging with K-Fold Cross Validation : 0.7904722222222222
       Confusion Matrix : 
[[ 982.5  364.4  400.2   38.9]
 [ 377.1 3752.9  102.6   73.4]
 [ 414.6  125.9 3685.    74.5]
 [  63.   115.7  112.6  116.7]]
Overall time needed for decision tree with gain ratio and Bagging with K-Fold Cross Validation : 1957.092261314392  miliseconds


***4) Boosting with cross validation***

In [ ]:
from sklearn.model_selection import cross_validate
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.ensemble import AdaBoostClassifier

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']

x = DATA[feature_cols] # Features
y = DATA.label # Target variable

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0
timee = 0

scoring = ['accuracy', 'f1_weighted', 'precision_weighted', 'recall_weighted']

for i in range(10):
  test_start = time()
  kfold = model_selection.KFold(n_splits=10, shuffle=True, random_state=i)
  dt = DecisionTreeClassifier(criterion="entropy")
  model = AdaBoostClassifier(base_estimator= dt)

  results = model_selection.cross_validate(model, X, y, cv=kfold, scoring=scoring)
  test_finish = time()
  
  accuracy = accuracy + results['test_accuracy'].mean()
  f1 = f1 + results['test_f1_weighted'].mean()
  precision = precision + results['test_precision_weighted'].mean()
  recall = recall + results['test_recall_weighted'].mean()
  timee = timee + test_finish-test_start

  y_pred = cross_val_predict(model, X, y, cv=kfold)
  Confusion_Matrix = Confusion_Matrix + confusion_matrix(y, y_pred)

print("Overall accuracy for decision tree with Boosting with K-Fold Cross Validation :", accuracy/10)
print("Overall f1_score for decision tree with Boosting with K-Fold Cross Validation :", f1/10)
print("Overall precision_score for decision tree with Boosting with K-Fold Cross Validation :", precision/10)
print("Overall recall_score for decision tree with Boosting with K-Fold Cross Validation :", recall/10)

print("       Confusion Matrix : ")
print(Confusion_Matrix/10)

print("Overall time needed for decision tree with Boosting with K-Fold Cross Validation :", ((timee/10)*10*10*10), " miliseconds")


Overall accuracy for decision tree with Boosting with K-Fold Cross Validation : 0.7430000000000001
Overall f1_score for decision tree with Boosting with K-Fold Cross Validation : 0.7471670069283624
Overall precision_score for decision tree with Boosting with K-Fold Cross Validation : 0.7526061857456584
Overall recall_score for decision tree with Boosting with K-Fold Cross Validation : 0.7430000000000001
       Confusion Matrix : 
[[ 880.7  409.3  419.    77. ]
 [ 451.5 3538.6  174.4  141.5]
 [ 508.6  168.7 3478.6  144.1]
 [  69.2   95.7  110.8  132.3]]
Overall time needed for decision tree with Boosting with K-Fold Cross Validation : 405.2299499511719  miliseconds


# ***Decision Tree Using Gini Index***

***1) With Holdout Method***

In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']


X = DATA[feature_cols] # Features
y = DATA.label # Target variable

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0
timee = 0

for x in range(10):
  test_start = time()
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=x) # 80% training and 20% test

  # Create Decision Tree classifer object
  clf = DecisionTreeClassifier(criterion="gini")

  # Train Decision Tree Classifer
  clf = clf.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = clf.predict(X_test)
  
  accuracy = accuracy + metrics.accuracy_score(y_test, y_pred)
  f1 = f1 + f1_score(y_test, y_pred, average='weighted')
  precision = precision + precision_score(y_test, y_pred, average='weighted')
  recall = recall + recall_score(y_test, y_pred, average='weighted')
  Confusion_Matrix = Confusion_Matrix + confusion_matrix(y_test, y_pred)
  test_finish = time()
  timee = timee + test_finish-test_start

print("Overall accuracy for decision tree with gini index and hold out method(10 times) :", accuracy/10)
print("Overall f1_score for decision tree with gini index and hold out method(10 times) :", f1/10)
print("Overall precision_score for decision tree with gini index and hold out method(10 times) :", precision/10)
print("Overall recall_score for decision tree with gini index and hold out method(10 times) :", recall/10)

print("       Confusion Matrix : ")
print(Confusion_Matrix/10)

print("Overall time needed for decision tree with gini index and hold out method(10 times) :", ((timee/10)*10*10*10), " miliseconds")


Overall accuracy for decision tree with gini index and hold out method(10 times) : 0.7405092592592593
Overall f1_score for decision tree with gini index and hold out method(10 times) : 0.7454981060893098
Overall precision_score for decision tree with gini index and hold out method(10 times) : 0.751649111111863
Overall recall_score for decision tree with gini index and hold out method(10 times) : 0.7405092592592593
       Confusion Matrix : 
[[171.6  75.7  88.   14.6]
 [ 97.3 703.1  38.9  29.5]
 [102.8  30.4 697.6  27.8]
 [ 13.3  20.9  21.3  27.2]]
Overall time needed for decision tree with gini index and hold out method(10 times) : 31.38277530670166  miliseconds


***2) With K Fold Cross-validation Method***

In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn import model_selection
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import *

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']

X = DATA[feature_cols] # Features
y = DATA.label # Target variable

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0
timee = 0

scoring = ['accuracy', 'f1_weighted', 'precision_weighted', 'recall_weighted']

for i in range(10):
  test_start = time()
  kfold = model_selection.KFold(n_splits=5, shuffle=True, random_state = i )
  model = DecisionTreeClassifier(criterion="gini")

  results = model_selection.cross_validate(model, X, y, cv=kfold, scoring=scoring)
  accuracy = accuracy + results['test_accuracy'].mean()
  f1 = f1 + results['test_f1_weighted'].mean()
  precision = precision + results['test_precision_weighted'].mean()
  recall = recall + results['test_recall_weighted'].mean()
  test_finish = time()
  timee = timee + test_finish-test_start

  y_pred = cross_val_predict(model, X, y, cv=kfold)
  Confusion_Matrix = Confusion_Matrix + confusion_matrix(y, y_pred)

print("Overall accuracy for decision tree with gini index and K Fold cross valdiation(10 times) :", accuracy/10)
print("Overall f1_score for decision tree with gini index and K Fold cross valdiation(10 times) :", f1/10)
print("Overall precision_score for decision tree with gini index and K Fold cross valdiation(10 times) :", precision/10)
print("Overall recall_score for decision tree with gini index and K Fold cross valdiation(10 times) :", recall/10)

print("       Confusion Matrix : ")
print(Confusion_Matrix/10)

print("Overall time needed for decision tree with gini index and K Fold cross valdiation(10 times) :", ((timee/10)*10*10*10), " miliseconds")

Overall accuracy for decision tree with gini index and K Fold cross valdiation(10 times) : 0.7391111111111112
Overall f1_score for decision tree with gini index and K Fold cross valdiation(10 times) : 0.7434713429090583
Overall precision_score for decision tree with gini index and K Fold cross valdiation(10 times) : 0.7488503997491684
Overall recall_score for decision tree with gini index and K Fold cross valdiation(10 times) : 0.7391111111111112
       Confusion Matrix : 
[[ 880.4  397.6  434.6   73.4]
 [ 455.6 3510.5  186.7  153.2]
 [ 505.7  177.  3469.4  147.9]
 [  68.9  104.5  105.4  129.2]]
Overall time needed for decision tree with gini index and K Fold cross valdiation(10 times) : 139.58969116210938  miliseconds


 ***3) With Bagging Ensemble Method***

In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.ensemble import BaggingClassifier
from sklearn import model_selection
from sklearn.model_selection import KFold


col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']

x = DATA[feature_cols] # Features
y = DATA.label # Target variable

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0
timee = 0

scoring = ['accuracy', 'f1_weighted', 'precision_weighted', 'recall_weighted']

for i in range(10):
  test_start = time()
  kfold = model_selection.KFold(n_splits=10, shuffle=True, random_state=i)
  dt = DecisionTreeClassifier(criterion="gini")
  model = BaggingClassifier(base_estimator=dt, random_state=i)

  results = model_selection.cross_validate(model, X, y, cv=kfold, scoring=scoring)
  test_finish = time()

  accuracy = accuracy + results['test_accuracy'].mean()
  f1 = f1 + results['test_f1_weighted'].mean()
  precision = precision + results['test_precision_weighted'].mean()
  recall = recall + results['test_recall_weighted'].mean()
  timee = timee + test_finish-test_start

  y_pred = cross_val_predict(model, X, y, cv=kfold)
  Confusion_Matrix = Confusion_Matrix + confusion_matrix(y, y_pred)


print("Overall accuracy for decision tree with gain ratio and Bagging with K-Fold Cross Validation :", accuracy/10)
print("Overall f1_score for decision tree with gain ratio and Bagging with K-Fold Cross Validation :", f1/10)
print("Overall precision_score for decision tree with gain ratio and Bagging with K-Fold Cross Validation :", precision/10)
print("Overall recall_score for decision tree with gain ratio and Bagging with K-Fold Cross Validation :", recall/10)

print("       Confusion Matrix : ")
print(Confusion_Matrix/10)

print("Overall time needed for decision tree with gain ratio and Bagging with K-Fold Cross Validation :", ((timee/10)*10*10*10), " miliseconds")

Overall accuracy for decision tree with gain ratio and Bagging with K-Fold Cross Validation : 0.7885833333333333
Overall f1_score for decision tree with gain ratio and Bagging with K-Fold Cross Validation : 0.7869335159094929
Overall precision_score for decision tree with gain ratio and Bagging with K-Fold Cross Validation : 0.7865808012341375
Overall recall_score for decision tree with gain ratio and Bagging with K-Fold Cross Validation : 0.7885833333333333
       Confusion Matrix : 
[[ 983.1  364.7  398.    40.2]
 [ 380.6 3742.4  105.1   77.9]
 [ 422.1  123.2 3679.    75.7]
 [  66.6  114.6  114.6  112.2]]
Overall time needed for decision tree with gain ratio and Bagging with K-Fold Cross Validation : 1714.1935586929321  miliseconds


***4) With Boosting Ensemble Method***

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris
from sklearn.ensemble import AdaBoostClassifier

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']

x = DATA[feature_cols] # Features
y = DATA.label # Target variable

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0
timee = 0

scoring = ['accuracy', 'f1_weighted', 'precision_weighted', 'recall_weighted']

for i in range(10):
  test_start = time()

  kfold = model_selection.KFold(n_splits=10, shuffle=True, random_state=i)
  dt = DecisionTreeClassifier(criterion="gini")
  model = AdaBoostClassifier(base_estimator= dt, n_estimators=100)
  results = model_selection.cross_validate(model, X, y, cv=kfold, scoring=scoring)
  test_finish = time()
  
  accuracy = accuracy + results['test_accuracy'].mean()
  f1 = f1 + results['test_f1_weighted'].mean()
  precision = precision + results['test_precision_weighted'].mean()
  recall = recall + results['test_recall_weighted'].mean()
  
  timee = timee + test_finish-test_start

  y_pred = cross_val_predict(model, X, y, cv=kfold)
  Confusion_Matrix = Confusion_Matrix + confusion_matrix(y, y_pred)

print("Overall accuracy for decision tree with Boosting with K-Fold Cross Validation :", accuracy/10)
print("Overall f1_score for decision tree with Boosting with K-Fold Cross Validation :", f1/10)
print("Overall precision_score for decision tree with Boosting with K-Fold Cross Validation :", precision/10)
print("Overall recall_score for decision tree with Boosting with K-Fold Cross Validation :", recall/10)

print("       Confusion Matrix : ")
print(Confusion_Matrix/10)

print("Overall time needed for decision tree with Boosting with K-Fold Cross Validation :", ((timee/10)*10*10*10), " miliseconds")

Overall accuracy for decision tree with Boosting with K-Fold Cross Validation : 0.7454166666666667
Overall f1_score for decision tree with Boosting with K-Fold Cross Validation : 0.7493488450055377
Overall precision_score for decision tree with Boosting with K-Fold Cross Validation : 0.7544456426944691
Overall recall_score for decision tree with Boosting with K-Fold Cross Validation : 0.7454166666666667
       Confusion Matrix : 
[[ 889.5  390.7  437.5   68.3]
 [ 460.7 3546.5  168.   130.8]
 [ 525.8  165.  3473.4  135.8]
 [  62.7  109.   103.3  133. ]]
Overall time needed for decision tree with Boosting with K-Fold Cross Validation : 326.5333414077759  miliseconds


# ***Naive Bayes***



***1) With Holdout Method***




In [ ]:
import pandas as pd
from sklearn import metrics
from sklearn.metrics import *
from sklearn.model_selection import train_test_split  # Import train_test_split function
from sklearn.naive_bayes import GaussianNB
from time import time

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13',
             'att14', 'att15', 'att16', 'label']
DATA = pd.read_csv('Final_Data.csv', header=None, names=col_names)
feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12',
                'att13', 'att14', 'att15', 'att16']

X = DATA[feature_cols]  # Features
y = DATA.label  # Target variable

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0
timee = 0

for x in range(10):
    test_start = time()
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=x)  # 80% training and 20% test

    gnb = GaussianNB()
    gnb.fit(X_train, y_train.ravel())
    y_pred = gnb.predict(X_test)

    accuracy = accuracy + metrics.accuracy_score(y_test, y_pred)
    f1 = f1 + f1_score(y_test, y_pred, average='weighted')
    precision = precision + precision_score(y_test, y_pred, average='weighted')
    recall = recall + recall_score(y_test, y_pred, average='weighted')
    Confusion_Matrix = Confusion_Matrix + confusion_matrix(y_test, y_pred)
    test_finish = time()
    timee = timee + test_finish-test_start

print("Overall accuracy for Naive Bayes with hold out method :", accuracy/10)
print("Overall f1_score for Naive Bayes with hold out method :", f1/10)
print("Overall precision_score for Naive Bayes with hold out method :", precision/10)
print("Overall recall_score for Naive Bayes with hold out method :", recall/10)

print("       Confusion Matrix : ")
print(Confusion_Matrix/10)

print("Overall time needed for Naive Bayes with hold out method :", ((timee/10)*10*10*10), " miliseconds")




Overall accuracy for Naive Bayes with hold out method : 0.7819907407407408
Overall f1_score for Naive Bayes with hold out method : 0.729055644026288
Overall precision_score for Naive Bayes with hold out method : 0.7190577152364745
Overall recall_score for Naive Bayes with hold out method : 0.7819907407407408
       Confusion Matrix : 
[[ 51.7 140.8 157.4   0. ]
 [ 14.6 823.8  30.4   0. ]
 [ 19.4  25.6 813.6   0. ]
 [ 16.5  26.6  39.6   0. ]]
Overall time needed for Naive Bayes with hold out method : 16.830778121948242  miliseconds


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Pr

***2) With K-fold Cross Validation Method***

In [ ]:
import pandas as pd
from sklearn import model_selection
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
from sklearn.naive_bayes import GaussianNB
from time import time


col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
DATA = pd.read_csv('Final_Data.csv', header=None, names=col_names)
feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']

X = DATA[feature_cols] # Features
y = DATA.label # Target variable

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0
timee = 0

scoring = ['accuracy', 'f1_weighted', 'precision_weighted', 'recall_weighted']

for x in range (10):
    test_start = time()
    kfold = model_selection.KFold(n_splits=10, shuffle=True, random_state=x)
    gnb = GaussianNB()

    results = model_selection.cross_validate(gnb, X, y, cv=kfold, scoring=scoring)
    accuracy = accuracy + results['test_accuracy'].mean()
    f1 = f1 + results['test_f1_weighted'].mean()
    precision = precision + results['test_precision_weighted'].mean()
    recall = recall + results['test_recall_weighted'].mean()
    test_finish = time()
    timee = timee + test_finish - test_start

    y_pred = cross_val_predict(gnb, X, y, cv=kfold)
    Confusion_Matrix = Confusion_Matrix + confusion_matrix(y, y_pred)

print("Overall accuracy for Naive Bayes with k-fold cross validation :", accuracy / 10)
print("Overall f1_score for Naive Bayes with k-fold cross validation :", f1 / 10)
print("Overall precision_score for Naive Bayes with k-fold cross validation :", precision / 10)
print("Overall recall_score for Naive Bayes with k-fold cross validation :", recall / 10)

print("       Confusion Matrix : ")
print(Confusion_Matrix / 10)

print("Overall time needed for Naive Bayes with k-fold cross validation :", ((timee / 10) * 10 * 10 * 10), " miliseconds")


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Pr

Overall accuracy for Naive Bayes with k-fold cross validation : 0.7802222222222223
Overall f1_score for Naive Bayes with k-fold cross validation : 0.7270947945460494
Overall precision_score for Naive Bayes with k-fold cross validation : 0.718425775976114
Overall recall_score for Naive Bayes with k-fold cross validation : 0.7802222222222223
       Confusion Matrix : 
[[ 269.9  733.2  782.9    0. ]
 [  73.6 4097.3  135.1    0. ]
 [ 102.6  138.2 4059.2    0. ]
 [  77.5  142.2  188.3    0. ]]
Overall time needed for Naive Bayes with k-fold cross validation : 120.38891315460205  miliseconds


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Pr

***3) With Bagging Ensemble Method***

In [ ]:
import pandas as pd
from sklearn import metrics
from sklearn.metrics import *
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import BaggingClassifier
from time import time

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13',
             'att14', 'att15', 'att16', 'label']
DATA = pd.read_csv('Final_Data.csv', header=None, names=col_names)
feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12',
                'att13', 'att14', 'att15', 'att16']

X = DATA[feature_cols]  # Features
y = DATA.label  # Target variable

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0
timee = 0

for x in range(10):
    test_start = time()
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=x)  # 80% training and 20% test
    gnb = GaussianNB()
    model = BaggingClassifier(base_estimator=gnb, random_state=x)

    model = model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    accuracy = accuracy + metrics.accuracy_score(y_test, y_pred)
    f1 = f1 + f1_score(y_test, y_pred, average='weighted')
    precision = precision + precision_score(y_test, y_pred, average='weighted')
    recall = recall + recall_score(y_test, y_pred, average='weighted')
    Confusion_Matrix = Confusion_Matrix + confusion_matrix(y_test, y_pred)
    test_finish = time()
    timee = timee + test_finish - test_start

print("Overall accuracy for Naive Bayes with Bagging Ensemble Method :", accuracy / 10)
print("Overall f1_score for Naive Bayes with Bagging Ensemble Method :", f1 / 10)
print("Overall precision_score for Naive Bayes with Bagging Ensemble Method :", precision / 10)
print("Overall recall_score for Naive Bayes with Bagging Ensemble Method :", recall / 10)

print("       Confusion Matrix : ")
print(Confusion_Matrix / 10)

print("Overall time needed for Naive Bayes with Bagging Ensemble Method :", ((timee / 10) * 10 * 10 * 10), " miliseconds")

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Pr

Overall accuracy for Naive Bayes with Bagging Ensemble Method : 0.7819444444444443
Overall f1_score for Naive Bayes with Bagging Ensemble Method : 0.7286495311660636
Overall precision_score for Naive Bayes with Bagging Ensemble Method : 0.7192605946964935
Overall recall_score for Naive Bayes with Bagging Ensemble Method : 0.7819444444444443
       Confusion Matrix : 
[[ 51.1 141.5 157.3   0. ]
 [ 14.5 824.3  30.    0. ]
 [ 18.8  26.2 813.6   0. ]
 [ 16.2  27.1  39.4   0. ]]
Overall time needed for Naive Bayes with Bagging Ensemble Method : 92.2642707824707  miliseconds


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


***4) With Boosting Ensemble Method***

In [ ]:
import pandas as pd
from sklearn import model_selection
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from time import time

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13',
             'att14', 'att15', 'att16', 'label']
DATA = pd.read_csv('Final_Data.csv', header=None, names=col_names)
feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12',
                'att13', 'att14', 'att15', 'att16']

X = DATA[feature_cols]  # Features
y = DATA.label  # Target variable

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0
timee = 0

test_start = time()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1) # 80% training and 20% test

gnb = GaussianNB()
model = AdaBoostClassifier(base_estimator=gnb, random_state=0, algorithm='SAMME')
model = model.fit(X_train,y_train)

y_pred = model.predict(X_test)

test_finish = time()
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
Confusion_Matrix = confusion_matrix(y_test, y_pred)

timee = timee + test_finish-test_start

print("Overall accuracy for Naive Bayes with Boosting Ensemble Method :", accuracy)
print("Overall f1_score for Naive Bayes with Boosting Ensemble Method :", f1)
print("Overall precision_score for Naive Bayes with Boosting Ensemble Method :", precision)
print("Overall recall_score for Naive Bayes with Boosting Ensemble Method :", recall)

print("       Confusion Matrix : ")
print(Confusion_Matrix)

print("Overall time needed for Naive Bayes with Boosting Ensemble Method :", ((timee)*10*10*10), " miliseconds")

Overall accuracy for Naive Bayes with Boosting Ensemble Method : 0.7893518518518519
Overall f1_score for Naive Bayes with Boosting Ensemble Method : 0.7507747892816242
Overall precision_score for Naive Bayes with Boosting Ensemble Method : 0.7703745641302338
Overall recall_score for Naive Bayes with Boosting Ensemble Method : 0.7893518518518519
       Confusion Matrix : 
[[ 89 137 135   0]
 [ 31 801  16   0]
 [ 33  24 813   0]
 [ 19  25  35   2]]
Overall time needed for Naive Bayes with Boosting Ensemble Method : 171.62561416625977  miliseconds


# ***SVM***



***1) SVM With Holdout Method***


In [ ]:
import pandas as pd
import numpy as np
from time import time
from sklearn.metrics import *
from sklearn.model_selection import train_test_split 
from sklearn.svm import SVC

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

#DATA.info()
feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']

X = DATA[feature_cols] # Features
y = DATA.label # Target variable

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0
timee = 0

for x in range(10):
  test_start = time()
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=x) # 80% training and 20% test

  # Create Decision Tree classifer object
  model = SVC()

  # Train Decision Tree Classifer
  model = model.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = model.predict(X_test)
  
  accuracy = accuracy + accuracy_score(y_test, y_pred)
  f1 = f1 + f1_score(y_test, y_pred, average='weighted')
  precision = precision + precision_score(y_test, y_pred, average='weighted')
  recall = recall + recall_score(y_test, y_pred, average='weighted')
  Confusion_Matrix = confusion_matrix(y_test, y_pred)
  test_finish = time()
  timee = timee + test_finish-test_start

print("Overall accuracy for SVM with hold out method(10 times) :", accuracy/10)
print("Overall f1_score for SVM with hold out method(10 times) :", f1/10)
print("Overall precision_score for SVM with hold out method(10 times) :", precision/10)
print("Overall recall_score for SVM with hold out method(10 times) :", recall/10)

print("       Confusion Matrix : ")
print(Confusion_Matrix)

print("Overall time needed for SVM with hold out method(10 times) :", ((timee/10)*10*10*10), " miliseconds")

Overall accuracy for SVM with hold out method(10 times) : 0.8603703703703702
Overall f1_score for SVM with hold out method(10 times) : 0.8551754548954541
Overall precision_score for SVM with hold out method(10 times) : 0.8582395760064058
Overall recall_score for SVM with hold out method(10 times) : 0.8603703703703702
       Confusion Matrix : 
[[222  53  63   1]
 [ 44 811   3   6]
 [ 62   9 798   0]
 [ 24  16  20  28]]
Overall time needed for SVM with hold out method(10 times) : 2452.696180343628  miliseconds


***2) SVM With K-Fold Cross Validation Method***

In [ ]:
import pandas as pd
from time import time
from sklearn import model_selection
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import *
from sklearn.svm import SVC


col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']

X = DATA[feature_cols] # Features
y = DATA.label # Target variable

scoring = ['accuracy', 'f1_weighted', 'precision_weighted', 'recall_weighted']

test_start = time()
kfold = model_selection.KFold(n_splits=5, shuffle=True, random_state = 100 )
model = SVC()
results = model_selection.cross_validate(model, X, y, cv=kfold, scoring=scoring)
test_finish = time()

accuracy = results['test_accuracy'].mean()
f1 = results['test_f1_weighted'].mean()
precision = results['test_precision_weighted'].mean()
recall = results['test_recall_weighted'].mean()
timee = test_finish-test_start

y_pred = cross_val_predict(model, X, y, cv=kfold)
Confusion_Matrix = Confusion_Matrix + confusion_matrix(y, y_pred)

print("Accuracy for SVM with K-Fold cross validation:", accuracy)
print("F1_score for SVM with K-Fold cross validation:", f1)
print("Precision_score for SVM with K-Fold cross validation:", precision)
print("Recall_score for SVM with K-Fold cross validation:", recall)

print("       Confusion Matrix : ")
print(Confusion_Matrix)

print("Time needed for SVM with K-Fold cross validation:", ((timee)*10*10*10), " miliseconds")

5
Overall accuracy for SVM with K-Fold cross validation: 0.8613888888888889
Overall f1_score for SVM with K-Fold cross validation: 0.8556676588911707
Overall precision_score for SVM with K-Fold cross validation: 0.8586577800895476
Overall recall_score for SVM with K-Fold cross validation: 0.8613888888888889
       Confusion Matrix : 
[[2284  556  726    6]
 [ 458 8062   62   30]
 [ 510   90 7980   20]
 [ 200  148  188  280]]
Overall time needed for SVM with K-Fold cross validation: 11407.729387283325  miliseconds


***3) SVM Bagging With Holdout Method***




In [ ]:
import pandas as pd
from sklearn.metrics import *
from time import time
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']

X = DATA[feature_cols] # Features
y = DATA.label # Target variable


test_start = time()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10) # 80% training and 20% test

# Create Decision Tree classifer object
model = BaggingClassifier(base_estimator=SVC(), n_estimators=20, random_state=0)

# Train Decision Tree Classifer
model = model.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)

test_finish = time()  
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
Confusion_Matrix = confusion_matrix(y_test, y_pred)
timee = test_finish-test_start

print("Accuracy for SVM with Bagging implemented with Hold Out method :", accuracy)
print("F1_score for SVM with Bagging implemented with Hold Out method :", f1)
print("Precision_score for SVM with Bagging implemented with Hold Out method :", precision)
print("Recall_score for SVM with Bagging implemented with Hold Out method :", recall)

print("       Confusion Matrix : ")
print(Confusion_Matrix)

print("Time needed for SVM with Bagging implemented with Hold Out method :", ((timee)*10*10*10), " miliseconds")



Accuracy for SVM with Bagging implemented with Hold Out method : 0.8555555555555555
F1_score for SVM with Bagging implemented with Hold Out method : 0.8497112893830099
Precision_score for SVM with Bagging implemented with Hold Out method : 0.8523607419395607
Recall_score for SVM with Bagging implemented with Hold Out method : 0.8555555555555555
       Confusion Matrix : 
[[244  60  83   1]
 [ 57 796   5   3]
 [ 42   8 778   1]
 [ 20  17  15  30]]
Time needed for SVM with Bagging implemented with Hold Out method : 23194.76342201233  miliseconds


***4) SVM Boosting With Holdout Method***




In [ ]:
import pandas as pd
from time import time
from sklearn.model_selection import train_test_split
from sklearn.metrics import *
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']

X = DATA[feature_cols] # Features
y = DATA.label # Target variable


test_start = time()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= 10) # 80% training and 20% test

# Create Decision Tree classifer object
model = AdaBoostClassifier(base_estimator=SVC(probability=True), n_estimators=1, random_state= 100)

# Train Decision Tree Classifer
model = model.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)

test_finish = time()  
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
Confusion_Matrix = confusion_matrix(y_test, y_pred)
timee = test_finish-test_start

print("Accuracy for SVM with Boosting implemented with Hold Out method :", accuracy)
print("F1_score for SVM with Boosting implemented with Hold Out method :", f1)
print("Precision_score for SVM with Boosting implemented with Hold Out method :", precision)
print("Recall_score for SVM with Boosting implemented with Hold Out method :", recall)

print("       Confusion Matrix : ")
print(Confusion_Matrix)

print("Time needed for SVM with Boosting implemented with Hold Out method :", ((timee)*10*10*10), " miliseconds")


Accuracy for SVM with Boosting implemented with Hold Out method : 0.8074074074074075
F1_score for SVM with Boosting implemented with Hold Out method : 0.8099544386965715
Precision_score for SVM with Boosting implemented with Hold Out method : 0.8168348589701964
Recall_score for SVM with Boosting implemented with Hold Out method : 0.8074074074074075
       Confusion Matrix : 
[[263  72  49   4]
 [ 93 758   4   6]
 [ 88  16 700  25]
 [ 33  18   8  23]]
Time needed for SVM with Boosting implemented with Hold Out method : 31487.324714660645  miliseconds


# ***Artificial Neural Networks (Single Hidden Layer)***

**1) Single Hidden Layer ANN**


In [ ]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

dataset = loadtxt('labeled.csv', delimiter=',')

# split into input (X) and output (y) variables
X = dataset[:, 0:16]
y = dataset[:, 16]

# Define the keras model
# Default activator: linear
model = Sequential()
model.add(Dense(8, input_dim=16))
model.add(Dense(4))
model.add(Dense(1))

# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# fit the keras model on the dataset
# model.fit(X, y, epochs=100, batch_size=25)
model.fit(X, y, epochs=100, batch_size=32)

# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy * 100), '%')

Epoch 1/100
338/338 [==============================] - 1s 1ms/step - loss: -2.3954 - accuracy: 0.3747
Epoch 2/100
338/338 [==============================] - 0s 1ms/step - loss: -4.5743 - accuracy: 0.3951
Epoch 3/100
338/338 [==============================] - 0s 1ms/step - loss: -4.4893 - accuracy: 0.3990
Epoch 4/100
338/338 [==============================] - 0s 1ms/step - loss: -4.6682 - accuracy: 0.3991
Epoch 5/100
338/338 [==============================] - 0s 1ms/step - loss: -4.5875 - accuracy: 0.4012
Epoch 6/100
338/338 [==============================] - 0s 1ms/step - loss: -4.6966 - accuracy: 0.3960
Epoch 7/100
338/338 [==============================] - 0s 1ms/step - loss: -4.5555 - accuracy: 0.3984
Epoch 8/100
338/338 [==============================] - 0s 1ms/step - loss: -4.4726 - accuracy: 0.3986
Epoch 9/100
338/338 [==============================] - 0s 1ms/step - loss: -4.5463 - accuracy: 0.4002
Epoch 10/100
338/338 [==============================] - 0s 1ms/step - loss: -4.625

**2) Single Hidden Layer ANN with Holdout**

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import *
from sklearn.neural_network import MLPClassifier
from time import time

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13',
             'att14', 'att15', 'att16', 'label']
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12',
                'att13', 'att14', 'att15', 'att16']

X = DATA[feature_cols]
y = DATA.label

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0

test_start = time()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

clf = MLPClassifier(solver='adam', hidden_layer_sizes=(4,), max_iter=100, random_state=0)

clf = clf.fit(X_train, y_train)

# Predict the response for test dataset
y_pred = clf.predict(X_test)

accuracy = accuracy + accuracy_score(y_test, y_pred)
f1 = f1 + f1_score(y_test, y_pred, average='weighted')
precision = precision + precision_score(y_test, y_pred, average='weighted')
recall = recall + recall_score(y_test, y_pred, average='weighted')
Confusion_Matrix = Confusion_Matrix + confusion_matrix(y_test, y_pred)
test_finish = time()
time = test_finish - test_start

print("Accuracy:", accuracy)
print("F1 Score:", f1)
print("Precision:", precision)
print("Recall Score:", recall)

print("       Confusion Matrix : ")
print(Confusion_Matrix)

print("Execution Time :", (time * 10 * 10 * 10)," milliseconds")


Accuracy: 0.8166666666666667
F1 Score: 0.7972044842952907
Precision: 0.7793188737346011
Recall Score: 0.8166666666666667
       Confusion Matrix : 
[[169  86 106   0]
 [ 48 794   6   0]
 [ 59  10 801   0]
 [ 58  11  12   0]]
Execution Time : 1825.3228664398193  milliseconds


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**3) Single Hidden Layer ANN with Holdout and Bagging**

In [ ]:
import pandas as pd
import numpy as np
from time import time
from sklearn.metrics import *
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13',
             'att14', 'att15', 'att16', 'label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

# DATA.info()
feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12',
                'att13', 'att14', 'att15', 'att16']

X = DATA[feature_cols]  # Features
y = DATA.label  # Target variable

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0
timee = 0

for x in range(1):
    test_start = time()
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=x)
    ann = MLPClassifier(solver='adam', hidden_layer_sizes=(4, 1), max_iter=100, random_state=0)
    model = BaggingClassifier(base_estimator=ann, n_estimators=10, random_state=1)
    model = model.fit(X_train, y_train)

    # Predict the response for test dataset
    y_pred = model.predict(X_test)

    accuracy = accuracy + accuracy_score(y_test, y_pred)
    f1 = f1 + f1_score(y_test, y_pred, average='weighted')
    precision = precision + precision_score(y_test, y_pred, average='weighted')
    recall = recall + recall_score(y_test, y_pred, average='weighted')
    Confusion_Matrix = confusion_matrix(y_test, y_pred)
    test_finish = time()
    timee = timee + test_finish - test_start

print("Accuracy:", accuracy)
print("F1 Score:", f1)
print("Precision:", precision)
print("Recall:", recall)

print("       Confusion Matrix : ")
print(Confusion_Matrix)

print("Exec Time:", ((timee) * 10 * 10 * 10), " milliseconds")


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


# ***Artificial Neural Networks (Dual Hidden Layer)***

1) Dual Hidden Layer ANN

In [ ]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

# load the dataset
dataset = loadtxt('labeled.csv', delimiter=',')

# split into input (X) and output (y) variables
X = dataset[:, 0:16]
y = dataset[:, 16]

# Define the keras model
# Default activator: linear
model = Sequential()
model.add(Dense(16, input_dim=16))
model.add(Dense(8))
model.add(Dense(4))
model.add(Dense(1))

# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# fit the keras model on the dataset
# model.fit(X, y, epochs=100, batch_size=25)
model.fit(X, y, epochs=100, batch_size=32)

# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy * 100))


Epoch 1/100
338/338 [==============================] - 1s 1ms/step - loss: 2.1737 - accuracy: 0.3197
Epoch 2/100
338/338 [==============================] - 0s 1ms/step - loss: -4.4630 - accuracy: 0.4049
Epoch 3/100
338/338 [==============================] - 0s 1ms/step - loss: -4.5581 - accuracy: 0.3938
Epoch 4/100
338/338 [==============================] - 0s 1ms/step - loss: -4.4737 - accuracy: 0.4107
Epoch 5/100
338/338 [==============================] - 0s 1ms/step - loss: -4.8036 - accuracy: 0.3972
Epoch 6/100
338/338 [==============================] - 0s 1ms/step - loss: -4.6911 - accuracy: 0.4057
Epoch 7/100
338/338 [==============================] - 0s 1ms/step - loss: -4.7068 - accuracy: 0.4028
Epoch 8/100
338/338 [==============================] - 0s 1ms/step - loss: -4.7485 - accuracy: 0.3986
Epoch 9/100
338/338 [==============================] - 0s 1ms/step - loss: -4.8618 - accuracy: 0.3973
Epoch 10/100
338/338 [==============================] - 0s 1ms/step - loss: -4.7710

**2) Dual Hidden Layer ANN with Holdout**

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import *
from sklearn.neural_network import MLPClassifier
from time import time

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13',
             'att14', 'att15', 'att16', 'label']
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12',
                'att13', 'att14', 'att15', 'att16']

X = DATA[feature_cols]
y = DATA.label

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0

test_start = time()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

clf = MLPClassifier(solver='adam', hidden_layer_sizes=(8,4), max_iter=100, random_state=0)

clf = clf.fit(X_train, y_train)

# Predict the response for test dataset
y_pred = clf.predict(X_test)

accuracy = accuracy + accuracy_score(y_test, y_pred)
f1 = f1 + f1_score(y_test, y_pred, average='weighted')
precision = precision + precision_score(y_test, y_pred, average='weighted')
recall = recall + recall_score(y_test, y_pred, average='weighted')
Confusion_Matrix = Confusion_Matrix + confusion_matrix(y_test, y_pred)
test_finish = time()
time = test_finish - test_start

print("Accuracy:", accuracy)
print("F1 Score:", f1)
print("Precision:", precision)
print("Recall Score:", recall)

print("       Confusion Matrix : ")
print(Confusion_Matrix)

print("Execution Time :", (time * 10 * 10 * 10)," milliseconds")


Accuracy: 0.8314814814814815
F1 Score: 0.8185808202728221
Precision: 0.806699396150257
Recall Score: 0.8314814814814815
       Confusion Matrix : 
[[212  81  68   0]
 [ 59 788   1   0]
 [ 71   3 796   0]
 [ 69   8   4   0]]
Execution Time : 8080.298185348511  milliseconds


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**3) Dual Hidden Layer ANN with Holdout and Bagging**

In [ ]:
import pandas as pd
import numpy as np
from time import time
from sklearn.metrics import *
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13',
             'att14', 'att15', 'att16', 'label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

# DATA.info()
feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12',
                'att13', 'att14', 'att15', 'att16']

X = DATA[feature_cols]  # Features
y = DATA.label  # Target variable

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0
timee = 0

for x in range(1):
    test_start = time()
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=x)
    ann = MLPClassifier(solver='adam', hidden_layer_sizes=(8, 4), max_iter=100, random_state=0)
    model = BaggingClassifier(base_estimator=ann, n_estimators=10, random_state=1)
    model = model.fit(X_train, y_train)

    # Predict the response for test dataset
    y_pred = model.predict(X_test)

    accuracy = accuracy + accuracy_score(y_test, y_pred)
    f1 = f1 + f1_score(y_test, y_pred, average='weighted')
    precision = precision + precision_score(y_test, y_pred, average='weighted')
    recall = recall + recall_score(y_test, y_pred, average='weighted')
    Confusion_Matrix = confusion_matrix(y_test, y_pred)
    test_finish = time()
    timee = timee + test_finish - test_start

print("Accuracy:", accuracy)
print("F1 Score:", f1)
print("Precision:", precision)
print("Recall:", recall)

print("       Confusion Matrix : ")
print(Confusion_Matrix)

print("Exec Time:", ((timee) * 10 * 10 * 10), " milliseconds")


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Accuracy: 0.8458333333333333
F1 Score: 0.8304971703243709
Precision: 0.815846560327202
Recall: 0.8458333333333333
       Confusion Matrix : 
[[187  61  90   0]
 [ 40 799   9   0]
 [ 55   2 841   0]
 [ 65   1  10   0]]
Exec Time: 23953.698873519897  milliseconds


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# ***Ensembling Methods***

***1) Ensembling With Bagging Classifier Methods***


In [ ]:
import pandas as pd
from sklearn import model_selection
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import VotingClassifier

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']

x = DATA[feature_cols] # Features
y = DATA.label # Target variable

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=100)

# Instantiate models
gnb = BaggingClassifier(base_estimator=GaussianNB(), n_estimators=10, random_state=0)
SVM = BaggingClassifier(base_estimator=SVC(probability=True), n_estimators=10, random_state=0)
dt = BaggingClassifier(base_estimator=DecisionTreeClassifier(criterion="entropy"), n_estimators=10, random_state=0)
ANN_1 = BaggingClassifier(base_estimator = MLPClassifier(solver='adam', hidden_layer_sizes=(5, 1), max_iter=1000), n_estimators=10, random_state=0)


# Define the list classifiers
classifiers = [('Artifical Neural Network', ANN_1), ('Support Vector Machine', SVM),('Classification Tree', dt), ('Gaussian Naive Bayes', gnb)]

# Iterate over the pre-defined list of classifiers
#for clf_name, clf in classifiers:    
    #_ = clf.fit(X_train, y_train)    
    #y_pred = clf.predict(X_test)
    #accuracy = accuracy_score(y_test, y_pred) 
    #print('{:s} : {:.3f}'.format(clf_name, accuracy))

test_start = time()
final_model = VotingClassifier(estimators=classifiers, voting='soft')     
final_model.fit(X_train, y_train) 

y_pred = final_model.predict(X_test)
test_finish = time() 

# Calculate accuracy score
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
Confusion_Matrix = confusion_matrix(y_test, y_pred)
timee = test_finish-test_start

#print('Voting Classifier: {:.3f}'.format(accuracy))
print('Accuracy for voting classifier combined with bagging methods : ', accuracy)
print('F1_score for voting classifier combined with bagging methods : ', f1)
print('Precision score for voting classifier combined with bagging methods : ', precision)
print('Recall for voting classifier combined with bagging methods : ', recall)
print ("         Confusion Matrix : ")
print(Confusion_Matrix)
print('Time required for voting classifier combined with bagging methods : ', timee, " seconds")

Accuracy for voting classifier combined with bagging methods :  0.8472222222222222
F1_score for voting classifier combined with bagging methods :  0.8319431926576162
Precision score for voting classifier combined with bagging methods :  0.8371148767360922
Recall for voting classifier combined with bagging methods :  0.8472222222222222
         Confusion Matrix : 
[[197  81  99   2]
 [ 32 801   8   3]
 [ 30   8 814   0]
 [ 23  18  26  18]]
Time required for voting classifier combined with bagging methods :  131.58692336082458


***2) Ensembling With Boosting Classifier Methods***


In [ ]:
import pandas as pd
from sklearn import model_selection
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import VotingClassifier

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']

x = DATA[feature_cols] # Features
y = DATA.label # Target variable

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=100)

# Instantiate models
gnb = AdaBoostClassifier(base_estimator=GaussianNB(), n_estimators=10, random_state=0)
dts = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(criterion="gini"), n_estimators=10, random_state=0)
SVM = AdaBoostClassifier(base_estimator=SVC(probability=True), n_estimators=2, random_state=0)

# Define the list classifiers
classifiers = [('Support Vector Machine', SVM),('Classification Tree', dts), ('Gaussian Naive Bayes', gnb)]

# Iterate over the pre-defined list of classifiers
#for clf_name, clf in classifiers:    
    #_ = clf.fit(X_train, y_train)    
    #y_pred = clf.predict(X_test)
    #accuracy = accuracy_score(y_test, y_pred) 
    #print('{:s} : {:.3f}'.format(clf_name, accuracy))

test_start = time()
final_model = VotingClassifier(estimators=classifiers, voting='soft')     
final_model.fit(X_train, y_train) 

y_pred = final_model.predict(X_test)
test_finish = time() 

# Calculate accuracy score
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
Confusion_Matrix = confusion_matrix(y_test, y_pred)
timee = test_finish-test_start

#print('Voting Classifier: {:.3f}'.format(accuracy))
print('Accuracy for voting classifier combined with boosting methods : ', accuracy)
print('F1_score for voting classifier combined with boosting methods : ', f1)
print('Precision score for voting classifier combined with boosting methods : ', precision)
print('Recall for voting classifier combined with boosting methods : ', recall)
print ("         Confusion Matrix : ")
print(Confusion_Matrix)
print('Time required for voting classifier combined with boosting methods : ', timee, " seconds")

Accuracy for voting classifier combined with boosting methods :  0.7421296296296296
F1_score for voting classifier combined with boosting methods :  0.7455377727969071
Precision score for voting classifier combined with boosting methods :  0.7494601031879936
Recall for voting classifier combined with boosting methods :  0.7421296296296296
         Confusion Matrix : 
[[186  80 100  13]
 [ 99 684  24  37]
 [ 94  24 707  27]
 [ 14  23  22  26]]
Time required for voting classifier combined with boosting methods :  61.37003183364868


***3) Ensembling With Best Accuracy Classifiers Method***


In [ ]:
import pandas as pd
from sklearn import model_selection
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import VotingClassifier

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']

x = DATA[feature_cols] # Features
y = DATA.label # Target variable

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=100)

# Instantiate models
gnb = AdaBoostClassifier(base_estimator=GaussianNB(), n_estimators=10, random_state=0)
dts = BaggingClassifier(base_estimator=DecisionTreeClassifier(criterion="entropy"), n_estimators=10, random_state=0)
SVM = SVC(probability=True)
ANN_1 = BaggingClassifier(base_estimator = MLPClassifier(solver='adam', hidden_layer_sizes=(8,4), max_iter=1000), n_estimators=10, random_state=0)

# Define the list classifiers
classifiers = [('Support Vector Machine', SVM), ('Artifical Neural Network', ANN_1), ('Classification Tree', dt), ('Gaussian Naive Bayes', gnb)]

# Iterate over the pre-defined list of classifiers
#for clf_name, clf in classifiers:    
    #_ = clf.fit(X_train, y_train)    
    #y_pred = clf.predict(X_test)
    #accuracy = accuracy_score(y_test, y_pred) 
    #print('{:s} : {:.3f}'.format(clf_name, accuracy))

test_start = time()
final_model = VotingClassifier(estimators=classifiers, voting='soft')     
final_model.fit(X_train, y_train) 

y_pred = final_model.predict(X_test)
test_finish = time() 

accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
Confusion_Matrix = confusion_matrix(y_test, y_pred)
timee = test_finish-test_start

#print('Voting Classifier: {:.3f}'.format(accuracy))
print('Accuracy for voting classifier combined with best methods : ', accuracy)
print('F1_score for voting classifier combined with best methods : ', f1)
print('Precision score for voting classifier combined with best methods : ', precision)
print('Recall for voting classifier combined with best methods : ', recall)
print ("         Confusion Matrix : ")
print(Confusion_Matrix)
print('Time required for voting classifier combined with best methods : ', timee, " seconds")

Accuracy for voting classifier combined with best methods :  0.8546296296296296
F1_score for voting classifier combined with best methods :  0.8471829274845076
Precision score for voting classifier combined with best methods :  0.8476163377774618
Recall for voting classifier combined with best methods :  0.8546296296296296
         Confusion Matrix : 
[[222  66  89   2]
 [ 43 788   7   6]
 [ 41   7 803   1]
 [ 18  17  17  33]]
Time required for voting classifier combined with best methods :  93.20690989494324


# Yeni Bölüm

import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn.metrics import *
from time import time

col_names = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16','label']
# load dataset
DATA = pd.read_csv("Final_Data.csv", header=None, names=col_names)

#DATA.info()
feature_cols = ['att1', 'att2', 'att3', 'att4', 'att5', 'att6', 'att7', 'att8', 'att9', 'att10', 'att11', 'att12', 'att13', 'att14', 'att15', 'att16']

X = DATA[feature_cols] # Features
y = DATA.label # Target variable

accuracy = 0
Confusion_Matrix = 0
f1 = 0
precision = 0
recall = 0
timee = 0

for x in range(10):
  test_start = time()
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=x) # 80% training and 20% test

  # Create Decision Tree classifer object
  clf = DecisionTreeClassifier(criterion="entropy")

  # Train Decision Tree Classifer
  clf = clf.fit(X_train, y_train)

  #Predict the response for test dataset
  y_pred = clf.predict(X_test)
  
  accuracy = accuracy + accuracy_score(y_test, y_pred)
  f1 = f1 + f1_score(y_test, y_pred, average='weighted')
  precision = precision + precision_score(y_test, y_pred, average='weighted')
  recall = recall + recall_score(y_test, y_pred, average='weighted')
  Confusion_Matrix = Confusion_Matrix + confusion_matrix(y_test, y_pred)
  test_finish = time()
  timee = timee + test_finish-test_start

print("Overall accuracy for decision tree with gain ratio and hold out method(10 times) :", accuracy/10)
print("Overall f1_score for decision tree with gain ratio and hold out method(10 times) :", f1/10)
print("Overall precision_score for decision tree with gain ratio and hold out method(10 times) :", precision/10)
print("Overall recall_score for decision tree with gain ratio and hold out method(10 times) :", recall/10)

print("       Confusion Matrix : ")
print(Confusion_Matrix/10)

print("Overall time needed for decision tree with gain ratio and hold out method(10 times) :", ((timee/10)*10*10*10), " miliseconds")